name: Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svg_out_path: dist/github-contribution-grid-snake.svg
